# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Force Publish to NPM (全量 major 升级)

on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: choice
                description: Who to greet
                options:
                    - major
                    - minor
                    - patch
            time:
                description: version 触发次数

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: branch
            - uses: actions/setup-node@v3
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm install
            - run: npm install pnpm -g
            - run: node ./scripts/build.mjs --version=${{github.event.inputs.version}} --time=${{github.event.inputs.time}} --mode=rebuild
            - run: pnpm --filter @chinese-fonts/* publish --access public  --no-git-checks
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "自动打包完成"
                  git push
